<?php

namespace Tests\Core;

use tp_logger;
use transposh_utils;
use WP_UnitTestCase;

ini_set( "include_path", "../core" . PATH_SEPARATOR . "../../core" . PATH_SEPARATOR . ini_get( "include_path" ) );
define( "DEBUG", 5 );
//require_once 'PHPUnit/Framework.php';
require_once dirname( __FILE__ ) . '/../../core/utils.php';

/**
 * Test class for utils.
 * Generated by PHPUnit on 2009-06-15 at 13:21:30.
 */
class Utils_Tests extends WP_UnitTestCase {

	/**
	 * @var    utils
	 * @access protected
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp(): void {
		$GLOBALS['logger']              = tp_logger::getInstance( true );
		$GLOBALS['logger']->show_caller = true;
		$GLOBALS['logger']->set_debug_level( 5 );
		$GLOBALS['logger']->eolprint = true;
		$GLOBALS['logger']->printout = true;
	}

	public function testRewriteURL() {
		$edit        = false;
		$params_only = false;
		$homeurl     = "http://transposh.org";
		$permalinks  = true;
		$this->assertEquals( "/he/", transposh_utils::rewrite_url_lang_param( "", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test", transposh_utils::rewrite_url_lang_param( "/test", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test/", transposh_utils::rewrite_url_lang_param( "/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test/", transposh_utils::rewrite_url_lang_param( "/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test/", transposh_utils::rewrite_url_lang_param( "/en/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/zh-tw/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/37/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/37/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh-tw&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&amp;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&#038;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?cat=y", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "he", $edit, $params_only ) );
	}

	public function testRewriteURLedit() {
		$edit        = true;
		$params_only = false;
		$homeurl     = "http://transposh.org";
		$permalinks  = true;
		$this->assertEquals( "/he/?edit=1", transposh_utils::rewrite_url_lang_param( "", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/?edit=1", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test?edit=1", transposh_utils::rewrite_url_lang_param( "/test", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test/?edit=1", transposh_utils::rewrite_url_lang_param( "/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test/?edit=1", transposh_utils::rewrite_url_lang_param( "/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/test/?edit=1", transposh_utils::rewrite_url_lang_param( "/en/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/zh-tw/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/37/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/37/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh-tw&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&amp;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&#038;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/he/?cat=y&edit=1", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "he", $edit, $params_only ) );
	}

	public function testRewriteURLparams() {
		$edit        = false;
		$params_only = true;
		$homeurl     = "http://transposh.org";
		$permalinks  = true;
		$this->assertEquals( "?lang=he", transposh_utils::rewrite_url_lang_param( "", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/?lang=he", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test?lang=he", transposh_utils::rewrite_url_lang_param( "/test", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/?lang=he", transposh_utils::rewrite_url_lang_param( "/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/?lang=he", transposh_utils::rewrite_url_lang_param( "/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/?lang=he", transposh_utils::rewrite_url_lang_param( "/en/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/zh-tw/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/37/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/37/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh-tw&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&amp;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&#038;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/?cat=y&lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "he", $edit, $params_only ) );
	}

	public function testRewriteURLwithsubdir() {
		//$GLOBALS[home_url] = "http://transposh.org/test/";
		$edit        = false;
		$params_only = false;
		$homeurl     = "http://transposh.org/test/";
		$permalinks  = true;
		$this->assertEquals( "/he/", transposh_utils::rewrite_url_lang_param( "", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/he/", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/he/", transposh_utils::rewrite_url_lang_param( "/test", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/he/", transposh_utils::rewrite_url_lang_param( "/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/he/", transposh_utils::rewrite_url_lang_param( "/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/he/", transposh_utils::rewrite_url_lang_param( "/test/en/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/zh-tw/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/37/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/37/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh-tw&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&amp;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&#038;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/he/?cat=y", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "he", $edit, $params_only ) );

		$this->assertEquals( "/", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?cat=y", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "", $edit, $params_only ) );
	}

	public function testRewriteURLwithsubdir2() {
		//$GLOBALS[home_url] = "http://transposh.org/test/";
		$edit        = false;
		$params_only = true;
		$homeurl     = "http://transposh.org/test/";
		$permalinks  = true;
		$this->assertEquals( "?lang=he", transposh_utils::rewrite_url_lang_param( "", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/?lang=he", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test?lang=he", transposh_utils::rewrite_url_lang_param( "/test", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/?lang=he", transposh_utils::rewrite_url_lang_param( "/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/?lang=he", transposh_utils::rewrite_url_lang_param( "/test/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "/test/?lang=he", transposh_utils::rewrite_url_lang_param( "/test/en/?lang=en", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/he/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://www.islands.co.il/fr/", transposh_utils::rewrite_url_lang_param( "http://www.islands.co.il/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/he", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/he/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/zh-tw/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/37/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/37/", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh-tw&edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&amp;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&#038;edit=1", $homeurl, $permalinks, "he", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?cat=y&lang=he", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "he", $edit, $params_only ) );

		$this->assertEquals( "", transposh_utils::rewrite_url_lang_param( "", $homeurl, $permalinks, "", $edit, $params_only ) );
		$this->assertEquals( "/", transposh_utils::rewrite_url_lang_param( "/", $homeurl, $permalinks, "", $edit, $params_only ) );
		$this->assertEquals( "http://transposh.org/test/?cat=y", transposh_utils::rewrite_url_lang_param( "http://transposh.org/test/fr/?lang=zh&#038;edit=1&cat=y", $homeurl, $permalinks, "", $edit, $params_only ) );
	}

	public function testCleanupURL() {
		$homeurl = "http://www.algarve-abc.de/ferienhaus-westalgarve/";
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve/test", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en/test", $homeurl ) );
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve", $homeurl ) );
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en", $homeurl ) );
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve/", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en/", $homeurl ) );
		$this->assertEquals( "/ferienhaus-westalgarve/", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en/", $homeurl, true ) );
	}

	public function testCleanupURL2() {
		$homeurl     = "http://www.algarve-abc.de/ferienhaus-westalgarve/";
		$params_only = true;
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve/test", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en/test", $homeurl ) );
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve", $homeurl ) );
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en", $homeurl ) );
		$this->assertEquals( "http://www.algarve-abc.de/ferienhaus-westalgarve/", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en/", $homeurl ) );
		$this->assertEquals( "/ferienhaus-westalgarve/", transposh_utils::cleanup_url( "http://www.algarve-abc.de/ferienhaus-westalgarve/en/", $homeurl, true ) );
	}

	public function testCleanupURL3() {
		$homeurl = "";
		//$params_only = true;
		$this->assertEquals( "/test", transposh_utils::cleanup_url( "/he/test", $homeurl ) );
		//$this->assertEquals("/test",cleanup_url("he/test",$homeurl));
	}

	public function testCleanupURL4() {
		$homeurl = "http://www.algarve-abc.de";
		$this->assertEquals( "/", transposh_utils::cleanup_url( "/he", $homeurl, true ) );
	}

	public function testGetOriginalURL() {
		$callback = static function ( $str = "", $param = "" ) {
			return $str;
		};
		$this->assertEquals( "/", transposh_utils::get_original_url( "/", '', 'en', $callback ) );
		$this->assertEquals( "/test", transposh_utils::get_original_url( "/test", '', 'en', $callback ) );
		$this->assertEquals( "/test/", transposh_utils::get_original_url( "/test/", '', 'en', $callback ) );
		$this->assertEquals( "www.islands.co.il/he/test/", transposh_utils::get_original_url( "www.islands.co.il/he/test/", 'www.islands.co.il', 'en', $callback ) );
		$this->assertEquals( "http://www.islands.co.il/he/test/", transposh_utils::get_original_url( "http://www.islands.co.il/he/test/", 'http://www.islands.co.il', 'en', $callback ) );
	}

	public function testTranslateURL() {
		$callback = static function ( $str = "", $param = "" ) {
			return array( $str, '0' );
		};
		$this->assertEquals( "/", transposh_utils::translate_url( "/", '', 'en', $callback ) );
		$this->assertEquals( "/test", transposh_utils::translate_url( "/test", '', 'en', $callback ) );
		$this->assertEquals( "/test/", transposh_utils::translate_url( "/test/", '', 'en', $callback ) );
		$this->assertEquals( "www.islands.co.il/he/test/", transposh_utils::translate_url( "www.islands.co.il/he/test/", 'www.islands.co.il', 'en', $callback ) );
		$this->assertEquals( "www.islands.co.il?lang=he", transposh_utils::translate_url( "www.islands.co.il?lang=he", 'www.islands.co.il', 'en', $callback ) );
		$this->assertEquals( "http://www.islands.co.il/he/test/", transposh_utils::translate_url( "http://www.islands.co.il/he/test/", 'http://www.islands.co.il', 'en', $callback ) );
		$this->assertEquals( "http://www.islands.co.il/he/test/?edit=1", transposh_utils::translate_url( "http://www.islands.co.il/he/test/?edit=1", 'http://www.islands.co.il', 'en', $callback ) );
	}

	public function testGrabLanguage() {
		$home_url = "http://transposh.org";
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/he/test/", $home_url ) );
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/he", $home_url ) );
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/?lang=he", $home_url ) );
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/he/?lang=he", $home_url ) );
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/he/?lang=he&fakeparam=no", $home_url ) );
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/he/?fake=no&lang=he&fakeparam=no", $home_url ) );
		$this->assertEquals( "he", transposh_utils::get_language_from_url( "http://transposh.org/hello/test/?lang=he", $home_url ) );
	}

}